export const GET_ALL_SING_UP_PERSONAL_WORKOUTS = 'GET_ALL_SING_UP_PERSONAL_WORKOUTS';
export const FILTERING_PERSONAL_WORKOUTS = ' FILTERING_PERSONAL_WORKOUTS';
export const GET_SING_UP_PERSONAL_WORKOUTS_BY_COACH = 'GET_SING_UP_PERSONAL_WORKOUTS_BY_COACH';
