export const GET_ALL_LIMITED_SUBSCRIPTIONS = 'GET_ALL_LIMITED_SUBSCRIPTIONS';
export const GET_LIMITED_SUBSCRIPTIONS = 'GET_LIMITED_SUBSCRIPTIONS';
export const ADD_LIMITED_SUBSCRIPTION = 'ADD_LIMITED_SUBSCRIPTION';