export const GET_ALL_UNLIMITED_SUBSCRIPTIONS = 'GET_ALL_UNLIMITED_SUBSCRIPTIONS';
export const GET_UNLIMITED_SUBSCRIPTIONS = 'GET_UNLIMITED_SUBSCRIPTIONS';
export const ADD_UNLIMITED_SUBSCRIPTION = 'ADD_UNLIMITED_SUBSCRIPTION';
